"""changed columns on borrow

Revision ID: 00b6620c23fe
Revises: 890cc1d908a2
Create Date: 2025-11-04 16:22:51.283777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b6620c23fe'
down_revision: Union[str, Sequence[str], None] = '890cc1d908a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_borrows', sa.Column('fine_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_borrows', 'fine_rate')
    # ### end Alembic commands ###
