"""remove unique constraint

Revision ID: 0113d208d208
Revises: c95ede6eb8a5
Create Date: 2025-10-13 23:11:40.955155

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0113d208d208"
down_revision: Union[str, Sequence[str], None] = "c95ede6eb8a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_book_copy_user"), "book_borrows", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_book_copy_user"),
        "book_borrows",
        ["book_copy_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
