"""init

Revision ID: 072913ee4872
Revises:
Create Date: 2025-10-09 13:58:20.656394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "072913ee4872"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("publication", sa.String(), nullable=True),
        sa.Column("isbn", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("ACADEMIC", "NON_ACADEMIC", "REFERENCE", name="bookcategorytype"),
            nullable=False,
        ),
        sa.Column("grade", sa.String(), nullable=True),
        sa.Column("cover_image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_book_category_grade", "books", ["category", "grade"], unique=False
    )
    op.create_index("idx_book_title_author", "books", ["title", "author"], unique=False)
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.create_index(
        op.f("ix_books_cover_image_url"), "books", ["cover_image_url"], unique=False
    )
    op.create_index(op.f("ix_books_grade"), "books", ["grade"], unique=False)
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_index(
        op.f("ix_books_publication"), "books", ["publication"], unique=False
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("event_date", sa.DateTime(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_name"), "events", ["name"], unique=False)
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_genres_id"), "genres", ["id"], unique=True)
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("quote", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_author"), "quotes", ["author"], unique=False)
    op.create_index(op.f("ix_quotes_quote"), "quotes", ["quote"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("designation", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("book_title", sa.String(), nullable=True),
        sa.Column("cover_image_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_id"), "recommendations", ["id"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("roll_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "role", sa.Enum("STUDENT", "LIBRARIAN", name="userrole"), nullable=False
        ),
        sa.Column("graduating_year", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "user_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_name"), "users", ["name"], unique=False)
    op.create_index(
        op.f("ix_users_roll_number"), "users", ["roll_number"], unique=False
    )
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=True)
    op.create_table(
        "book_copies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_identifier", sa.String(), nullable=True),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("condition", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_book_copy_availability",
        "book_copies",
        ["book_id", "is_available"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_copies_unique_identifier"),
        "book_copies",
        ["unique_identifier"],
        unique=False,
    )
    op.create_table(
        "book_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("review_text", sa.String(), nullable=True),
        sa.Column("is_spam", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "idx_unique_book_user", "book_reviews", ["book_id", "user_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_reviews_book_id"), "book_reviews", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_book_reviews_review_text"),
        "book_reviews",
        ["review_text"],
        unique=False,
    )
    op.create_index(
        op.f("ix_book_reviews_user_id"), "book_reviews", ["user_id"], unique=False
    )
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "books_genre",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("book_id", "genre_id"),
    )
    op.create_index(
        op.f("ix_books_genre_book_id"), "books_genre", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_books_genre_genre_id"), "books_genre", ["genre_id"], unique=False
    )
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedbacks_feedback"), "feedbacks", ["feedback"], unique=False
    )
    op.create_index(
        op.f("ix_feedbacks_is_acknowledged"),
        "feedbacks",
        ["is_acknowledged"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedbacks_subject"), "feedbacks", ["subject"], unique=False
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"),
        "password_reset_tokens",
        ["id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_feedbacks_subject"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_is_acknowledged"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_feedback"), table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_books_genre_genre_id"), table_name="books_genre")
    op.drop_index(op.f("ix_books_genre_book_id"), table_name="books_genre")
    op.drop_table("books_genre")
    op.drop_table("bookmarks")
    op.drop_index(op.f("ix_book_reviews_user_id"), table_name="book_reviews")
    op.drop_index(op.f("ix_book_reviews_review_text"), table_name="book_reviews")
    op.drop_index(op.f("ix_book_reviews_book_id"), table_name="book_reviews")
    op.drop_index("idx_unique_book_user", table_name="book_reviews")
    op.drop_table("book_reviews")
    op.drop_index(op.f("ix_book_copies_unique_identifier"), table_name="book_copies")
    op.drop_index("idx_book_copy_availability", table_name="book_copies")
    op.drop_table("book_copies")
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_index(op.f("ix_users_roll_number"), table_name="users")
    op.drop_index(op.f("ix_users_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_recommendations_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_quotes_quote"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_author"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_genres_id"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(op.f("ix_events_name"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_publication"), table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_grade"), table_name="books")
    op.drop_index(op.f("ix_books_cover_image_url"), table_name="books")
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_index("idx_book_title_author", table_name="books")
    op.drop_index("idx_book_category_grade", table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###
