"""add: revision to the book_borrow

Revision ID: 13fb7d86fa16
Revises: 0113d208d208
Create Date: 2025-10-13 23:51:13.685858

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13fb7d86fa16"
down_revision: Union[str, Sequence[str], None] = "0113d208d208"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book_borrows", sa.Column("remark", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_borrows", "remark")
    # ### end Alembic commands ###
