"""add_returned_field

Revision ID: 1f41e8c95f5a
Revises: e87dc61b1db8
Create Date: 2025-10-09 15:25:07.667413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f41e8c95f5a"
down_revision: Union[str, Sequence[str], None] = "e87dc61b1db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_borrows",
        sa.Column("returned", sa.Boolean(), nullable=True, default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_borrows", "returned")
    # ### end Alembic commands ###
