"""books

Revision ID: 25eee93ca369
Revises: 579346267baa
Create Date: 2025-09-04 15:26:26.145548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25eee93ca369"
down_revision: Union[str, Sequence[str], None] = "579346267baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "book_copies", ["id"])
    op.create_unique_constraint(None, "books", ["id"])
    op.create_unique_constraint(None, "feedbacks", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedbacks", type_="unique")
    op.drop_constraint(None, "books", type_="unique")
    op.drop_constraint(None, "book_copies", type_="unique")
    # ### end Alembic commands ###
