"""add_book_borrow

Revision ID: 384a9e19c576
Revises: 072913ee4872
Create Date: 2025-10-09 13:59:40.171191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384a9e19c576'
down_revision: Union[str, Sequence[str], None] = '072913ee4872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_borrows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('fine_accumulated', sa.Integer(), nullable=True),
    sa.Column('times_renewable', sa.Integer(), nullable=True),
    sa.Column('times_renewed', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_borrows_book_copy_id'), 'book_borrows', ['book_copy_id'], unique=False)
    op.create_index(op.f('ix_book_borrows_user_id'), 'book_borrows', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'book_copies', ['id'])
    op.create_unique_constraint(None, 'book_reviews', ['id'])
    op.create_unique_constraint(None, 'bookmarks', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    op.create_unique_constraint(None, 'feedbacks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'bookmarks', type_='unique')
    op.drop_constraint(None, 'book_reviews', type_='unique')
    op.drop_constraint(None, 'book_copies', type_='unique')
    op.drop_index(op.f('ix_book_borrows_user_id'), table_name='book_borrows')
    op.drop_index(op.f('ix_book_borrows_book_copy_id'), table_name='book_borrows')
    op.drop_table('book_borrows')
    # ### end Alembic commands ###
