"""fine_status_column

Revision ID: 38a1e611667f
Revises: 1f41e8c95f5a
Create Date: 2025-10-09 17:40:06.849911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a1e611667f'
down_revision: Union[str, Sequence[str], None] = '1f41e8c95f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('book_borrows', sa.Column('fine_status', sa.Enum('UNPAID', 'PAID', name='finestatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_borrows', 'fine_status')
    # ### end Alembic commands ###
