"""disabled_to_status

Revision ID: 3d1b4aee2592
Revises: da335a04d706
Create Date: 2025-10-13 16:01:52.665581

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d1b4aee2592"
down_revision: Union[str, Sequence[str], None] = "da335a04d706"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "book_copies", ["id"])
    op.create_unique_constraint(None, "book_reviews", ["id"])
    op.create_unique_constraint(None, "bookmarks", ["id"])
    op.create_unique_constraint(None, "books", ["id"])
    op.create_unique_constraint(None, "feedbacks", ["id"])
    op.execute("ALTER TYPE finestatus ADD VALUE 'DISABLED' ")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedbacks", type_="unique")
    op.drop_constraint(None, "books", type_="unique")
    op.drop_constraint(None, "bookmarks", type_="unique")
    op.drop_constraint(None, "book_reviews", type_="unique")
    op.drop_constraint(None, "book_copies", type_="unique")
    # ### end Alembic commands ###
