"""books_genre_model

Revision ID: 485ebe960a52
Revises: 53cc7dda3af5
Create Date: 2025-09-04 16:10:03.604279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485ebe960a52'
down_revision: Union[str, Sequence[str], None] = '53cc7dda3af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_index(op.f('ix_books_genre_book_id'), 'books_genre', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_genre_genre_id'), 'books_genre', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_genre_genre_id'), table_name='books_genre')
    op.drop_index(op.f('ix_books_genre_book_id'), table_name='books_genre')
    op.drop_table('books_genre')
    # ### end Alembic commands ###
