"""books_update

Revision ID: 53cc7dda3af5
Revises: 25eee93ca369
Create Date: 2025-09-04 16:02:42.986884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cc7dda3af5'
down_revision: Union[str, Sequence[str], None] = '25eee93ca369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_copies', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('book_copies', sa.Column('condition', sa.String(), nullable=True))
    op.create_index('idx_book_copy_availability', 'book_copies', ['book_id', 'is_available'], unique=False)
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index('idx_book_category_grade', 'books', ['category', 'grade'], unique=False)
    op.create_index('idx_book_title_author', 'books', ['title', 'author'], unique=False)
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_book_title_author', table_name='books')
    op.drop_index('idx_book_category_grade', table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.drop_index('idx_book_copy_availability', table_name='book_copies')
    op.drop_column('book_copies', 'condition')
    op.drop_column('book_copies', 'is_available')
    # ### end Alembic commands ###
