"""update events model

Revision ID: 5c276102ed31
Revises: f5d4be649294
Create Date: 2025-10-15 17:18:02.008384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c276102ed31"
down_revision: Union[str, Sequence[str], None] = "f5d4be649294"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
