"""added book table

Revision ID: 5c8278fa6fb9
Revises: 4a078b5e02ef
Create Date: 2025-08-29 16:20:32.523381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8278fa6fb9'
down_revision: Union[str, Sequence[str], None] = '4a078b5e02ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dss_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publication', sa.String(), nullable=True),
    sa.Column('ISBN', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('ACADEMIC', 'NON_ACADEMIC', 'REFERENCE', name='bookcategorytype'), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('dss_book_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dss_book_id'], ['dss_books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_books_ISBN'), 'books', ['ISBN'], unique=False)
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_cover_image_url'), 'books', ['cover_image_url'], unique=False)
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.create_index(op.f('ix_books_grade'), 'books', ['grade'], unique=False)
    op.create_index(op.f('ix_books_publication'), 'books', ['publication'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_unique_constraint(None, 'feedbacks', ['id'])
    op.alter_column('teacher_recommendations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teacher_recommendations', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teacher_recommendations', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('teacher_recommendations', 'book_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_recommendations', 'book_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teacher_recommendations', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teacher_recommendations', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('teacher_recommendations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_publication'), table_name='books')
    op.drop_index(op.f('ix_books_grade'), table_name='books')
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_index(op.f('ix_books_cover_image_url'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_index(op.f('ix_books_ISBN'), table_name='books')
    op.drop_table('books')
    op.drop_table('dss_books')
    # ### end Alembic commands ###
