"""book borrow model

Revision ID: 890cc1d908a2
Revises: 98a7f3445a5c
Create Date: 2025-10-16 17:24:56.884265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890cc1d908a2'
down_revision: Union[str, Sequence[str], None] = '98a7f3445a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reserves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('RESERVED', 'BORROWED', 'BORROW_FAILED', name='bookreserveenum'), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_reserves')
    # ### end Alembic commands ###
