"""update book model

Revision ID: 93bfae2baf7a
Revises: 91a1960dc18d
Create Date: 2025-09-01 20:28:02.746239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bfae2baf7a'
down_revision: Union[str, Sequence[str], None] = '91a1960dc18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.drop_index(op.f('ix_books_ISBN'), table_name='books')
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_unique_constraint(None, 'books', ['id'])
    op.drop_constraint(op.f('books_dss_book_id_fkey'), 'books', type_='foreignkey')
    op.drop_column('books', 'ISBN')
    op.drop_column('books', 'dss_book_id')
    op.create_unique_constraint(None, 'dss_books', ['id'])
    op.create_unique_constraint(None, 'feedbacks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_constraint(None, 'dss_books', type_='unique')
    op.add_column('books', sa.Column('dss_book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('ISBN', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('books_dss_book_id_fkey'), 'books', 'dss_books', ['dss_book_id'], ['id'])
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.create_index(op.f('ix_books_ISBN'), 'books', ['ISBN'], unique=False)
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
