"""create quotes table

Revision ID: b05ce225c7bf
Revises: 1410ce3a0098
Create Date: 2025-07-29 16:02:22.282761

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b05ce225c7bf"
down_revision: Union[str, Sequence[str], None] = "1410ce3a0098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("quote", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotes_author"), "quotes", ["author"], unique=False)
    op.create_index(op.f("ix_quotes_quote"), "quotes", ["quote"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quotes_quote"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_author"), table_name="quotes")
    op.drop_table("quotes")
    # ### end Alembic commands ###
