"""removed teacher-recommendation model

Revision ID: b0db8217c6a4
Revises: 75a6927cab5f
Create Date: 2025-09-03 12:45:10.300478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b0db8217c6a4"
down_revision: Union[str, Sequence[str], None] = "75a6927cab5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_teacher_recommendations_id"), table_name="teacher_recommendations"
    )
    op.drop_table("teacher_recommendations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_recommendations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("designation", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("note", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("book_title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cover_image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("teacher_recommendations_pkey")),
    )
    op.create_index(
        op.f("ix_teacher_recommendations_id"),
        "teacher_recommendations",
        ["id"],
        unique=True,
    )
    # ### end Alembic commands ###
