"""recommendation model

Revision ID: b1fd3cf56d8c
Revises: 4a078b5e02ef
Create Date: 2025-09-03 12:41:24.549116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1fd3cf56d8c"
down_revision: Union[str, Sequence[str], None] = "4a078b5e02ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_copies_unique_identifier"), table_name="book_copies")
    op.drop_table("book_copies")
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_index(op.f("ix_books_cover_image_url"), table_name="books")
    op.drop_index(op.f("ix_books_genre"), table_name="books")
    op.drop_index(op.f("ix_books_grade"), table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_publication"), table_name="books")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_table("books")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('books_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("publication", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "category",
            postgresql.ENUM(
                "ACADEMIC", "NON_ACADEMIC", "REFERENCE", name="bookcategorytype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("genre", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("grade", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cover_image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("isbn", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="books_pkey"),
        sa.UniqueConstraint(
            "id",
            name="books_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_index(
        op.f("ix_books_publication"), "books", ["publication"], unique=False
    )
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=False)
    op.create_index(op.f("ix_books_grade"), "books", ["grade"], unique=False)
    op.create_index(op.f("ix_books_genre"), "books", ["genre"], unique=False)
    op.create_index(
        op.f("ix_books_cover_image_url"), "books", ["cover_image_url"], unique=False
    )
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.create_table(
        "book_copies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "unique_identifier", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("book_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("book_copies_book_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("book_copies_pkey")),
        sa.UniqueConstraint(
            "id",
            name=op.f("book_copies_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_book_copies_unique_identifier"),
        "book_copies",
        ["unique_identifier"],
        unique=False,
    )
    # ### end Alembic commands ###
