"""return date to books_borrow

Revision ID: c95ede6eb8a5
Revises: 3d1b4aee2592
Create Date: 2025-10-13 19:50:36.351533

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c95ede6eb8a5"
down_revision: Union[str, Sequence[str], None] = "3d1b4aee2592"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_borrows", sa.Column("returned_date", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_borrows", "returned_date")
    # ### end Alembic commands ###
