"""add_unique_constraint

Revision ID: e87dc61b1db8
Revises: 384a9e19c576
Create Date: 2025-10-09 14:36:11.354193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e87dc61b1db8"
down_revision: Union[str, Sequence[str], None] = "384a9e19c576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_book_copy_user", "book_borrows", ["book_copy_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_book_copy_user", "book_borrows", type_="unique")
    # ### end Alembic commands ###
