"""added password reset token table

Revision ID: eca6f030dcbb
Revises: 60e87a86720c
Create Date: 2025-08-20 18:14:26.784349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eca6f030dcbb"
down_revision: Union[str, Sequence[str], None] = "60e87a86720c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "feedbacks", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedbacks", type_="unique")
    # ### end Alembic commands ###
