"""update book review

Revision ID: f16428923740
Revises: 33c188fc148a
Create Date: 2025-09-15 13:11:18.910213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16428923740'
down_revision: Union[str, Sequence[str], None] = '33c188fc148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book_copies', ['id'])
    op.drop_index(op.f('idx_unique_book_user'), table_name='book_reviews')
    op.create_index('idx_unique_book_user', 'book_reviews', ['book_id', 'user_id'], unique=False)
    op.create_unique_constraint(None, 'book_reviews', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    op.create_unique_constraint(None, 'feedbacks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'book_reviews', type_='unique')
    op.drop_index('idx_unique_book_user', table_name='book_reviews')
    op.create_index(op.f('idx_unique_book_user'), 'book_reviews', ['book_id', 'user_id'], unique=True)
    op.drop_constraint(None, 'book_copies', type_='unique')
    # ### end Alembic commands ###
