"""genre model

Revision ID: f496a2de488a
Revises: 1b8dea7b04b8
Create Date: 2025-08-01 17:54:22.925814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f496a2de488a"
down_revision: Union[str, Sequence[str], None] = "1b8dea7b04b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "feedbacks", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedbacks", type_="unique")
    # ### end Alembic commands ###
