"""update events model

Revision ID: f5d4be649294
Revises: 13fb7d86fa16
Create Date: 2025-10-15 16:07:22.670785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5d4be649294"
down_revision: Union[str, Sequence[str], None] = "13fb7d86fa16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("time", sa.DateTime(), nullable=False))
    op.add_column("events", sa.Column("venue", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "venue")
    op.drop_column("events", "time")
    # ### end Alembic commands ###
